/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAIAgent,
  IAIAgentInterface,
} from "../../../contracts/interfaces/IAIAgent";

const _abi = [
  {
    inputs: [
      {
        components: [
          {
            internalType: "string",
            name: "action",
            type: "string",
          },
          {
            internalType: "bytes",
            name: "data",
            type: "bytes",
          },
        ],
        internalType: "struct IAIAgent.Decision",
        name: "action",
        type: "tuple",
      },
    ],
    name: "executeAction",
    outputs: [
      {
        components: [
          {
            internalType: "bool",
            name: "success",
            type: "bool",
          },
          {
            internalType: "string",
            name: "message",
            type: "string",
          },
        ],
        internalType: "struct IAIAgent.Result",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "context",
        type: "bytes",
      },
    ],
    name: "makeDecision",
    outputs: [
      {
        components: [
          {
            internalType: "string",
            name: "action",
            type: "string",
          },
          {
            internalType: "bytes",
            name: "data",
            type: "bytes",
          },
        ],
        internalType: "struct IAIAgent.Decision",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAIAgent__factory {
  static readonly abi = _abi;
  static createInterface(): IAIAgentInterface {
    return new Interface(_abi) as IAIAgentInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IAIAgent {
    return new Contract(address, _abi, runner) as unknown as IAIAgent;
  }
}
