/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDecision,
  IDecisionInterface,
} from "../../../contracts/interfaces/IDecision";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "decisionId",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "address",
        name: "executor",
        type: "address",
      },
    ],
    name: "DecisionExecuted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "decisionId",
        type: "uint256",
      },
    ],
    name: "DecisionValidated",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "decisionId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "target",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "executeDecision",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "decisionId",
        type: "uint256",
      },
    ],
    name: "getDecisionStatus",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "decisionId",
        type: "uint256",
      },
    ],
    name: "validateDecision",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IDecision__factory {
  static readonly abi = _abi;
  static createInterface(): IDecisionInterface {
    return new Interface(_abi) as IDecisionInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IDecision {
    return new Contract(address, _abi, runner) as unknown as IDecision;
  }
}
