codecov:
  max_report_age: off
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%
    changes:
      default:
        target: 80%

ignore:
  - "**/__tests__/**"
  - "**/__mocks__/**"
  - "**/dist/**"
  - "**/node_modules/**"
