/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as treasury from "./treasury";
export type { treasury };
export type { Lock } from "./Lock";
export type { SADLToken } from "./SADLToken";
export type { Proposal } from "./governance";
