/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IAIAgent {
  export type DecisionStruct = { action: string; data: BytesLike };

  export type DecisionStructOutput = [action: string, data: string] & {
    action: string;
    data: string;
  };

  export type ResultStruct = { success: boolean; message: string };

  export type ResultStructOutput = [success: boolean, message: string] & {
    success: boolean;
    message: string;
  };
}

export interface IAIAgentInterface extends Interface {
  getFunction(
    nameOrSignature: "executeAction" | "makeDecision"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "executeAction",
    values: [IAIAgent.DecisionStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "makeDecision",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "executeAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "makeDecision",
    data: BytesLike
  ): Result;
}

export interface IAIAgent extends BaseContract {
  connect(runner?: ContractRunner | null): IAIAgent;
  waitForDeployment(): Promise<this>;

  interface: IAIAgentInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  executeAction: TypedContractMethod<
    [action: IAIAgent.DecisionStruct],
    [IAIAgent.ResultStructOutput],
    "nonpayable"
  >;

  makeDecision: TypedContractMethod<
    [context: BytesLike],
    [IAIAgent.DecisionStructOutput],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "executeAction"
  ): TypedContractMethod<
    [action: IAIAgent.DecisionStruct],
    [IAIAgent.ResultStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "makeDecision"
  ): TypedContractMethod<
    [context: BytesLike],
    [IAIAgent.DecisionStructOutput],
    "nonpayable"
  >;

  filters: {};
}
